# Site
title: "Hugo Nogueira"
description: "Lead front-end engineer and agile manager. React, React Native and Node.js enthusiast. Principal front-end and Lead engineer @ <a href='http://infinitec.solutions'>Infinitec Solutions</a>. Berlin, Germany"
meta_description: "Hugo Nogueira, Software Engineer, Lead Front-end engineer, Senior ReactJs developer"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.png'
baseurl: 
google_analytics: 'UA-16818992-1'
disqus: 'hugomagalhes'
permalink: /blog/:title
exclude: ["README.md", "Gemfile", "Gemfile.lock", "node_modules", "package.json", "package-lock.json"]
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

# Authors
authors:
  hugo:
    name: Hugo
    display_name: Hugo Nogueira
    gravatar: 86d69b8300d46636769c0bf2c133796d
    email: hugomn@gmail.com
    web: https://www.hugomagalhaes.com
    twitter: https://twitter.com/hugomn
    description: "React, React Native and Node.js enthusiast. Principal front-end and Lead engineer @ infinitec.solutions. Berlin, DE"

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
  - jekyll-category-pages
  - jekyll-seo-tag
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown
highlighter: rouge

# Categories
category_path: "category" 
category_layout: "category_index.html"