# Site
title: "Hugo Nogueira"
description: "Senior software engineer and agile manager. React, and Node.js enthusiast. <br/> Engineering Lead @ <a href='https://www.bcgdv.com'>BCG Digital Ventures</a>. Berlin, Germany"
url: https://www.hugomagalhaes.com
meta_description: "Hugo Nogueira, Software Engineer, Lead Front-end engineer, Senior ReactJs developer"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.png'
baseurl: 
google_analytics: 'UA-16818992-1'
disqus: 'hugomagalhes'
permalink: /blog/:title
exclude: ["README.md", "Gemfile", "Gemfile.lock", "node_modules", "package.json", "package-lock.json"]
social:
  name: Hugo Nogueira
  links:
    - https://twitter.com/hugomn/
    - https://www.facebook.com/helloitshugo
    - https://www.instagram.com/hugomn/
    - https://github.com/hugomn
facebook:
  app_id: 2266339926985215
  publisher: 1294104205

# Authors
authors:
  Hugo Nogueira:
    name: Hugo Nogueira
    display_name: Hugo Nogueira
    gravatar: 86d69b8300d46636769c0bf2c133796d
    email: hugomn@gmail.com
    web: https://www.hugomagalhaes.com
    twitter: https://twitter.com/hugomn
    description: "Senior software engineer and agile manager. React, and Node.js enthusiast. <br/> Engineering Lead @ <a href='https://www.bcgdv.com'>BCG Digital Ventures</a>. Berlin, Germany"

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
  - jekyll-category-pages
  - jekyll-seo-tag
  - jekyll-polyglot
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 10
paginate_path: /page:num/
    
# Other
markdown: kramdown
highlighter: rouge

# Categories
category_path: "category" 
category_layout: "category_index.html"

# i18n
languages: ["en", "pt"]
default_lang: "en"
exclude_from_localization: ["javascript", "images", "css"]
parallel_localization: true